### ISSUE TITLE
Check metadata size of each object prior to upload/ build of a package

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#1022]
It has happened a couple times now but not nearly as sad as the most recent occurrence:

_(this is a rough estimate of the log and exception as I have already cleared my terminal)_
```
Copying: 100% [========================] 4.13TB/ 4.15TB

Error: Metadata size for object exceeds limit
```

It would be pretty useful to check the metadata size of each object during the build step so that I/ others don't run into this error again in the future.

**Comment by akarve** [comment]
Metadata sizes are no longer limited since they are no longer stored in the object Head.
