### ISSUE TITLE
Show commit message on file version dropdown

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#1261]
![image](https://user-images.githubusercontent.com/17132317/66589146-be06db00-eb42-11e9-8264-37c6bba16b09.png)

Displaying the commit messages on the file drop down would provide more context to which version is which.

**Comment by akarve** [comment]
This feature would require the metadata service, or a refactor in order to function. We would need a lookup function that goes from object to package. Also what if the object is in multiple packages? @JacksonMaxfield is this still of value or can we close?

**Comment by JacksonMaxfield** [comment]
I would put it very very low on priority list. No direct need. Just would be nice. Will close.
