### ISSUE TITLE
Error pushing to S3 when ServerSideEncryption required

### ISSUE THREAD

**Issue by jdprusa** [quiltdata/quilt#1326]
Currently there is no clear way to set ServerSideEncryption when pushing to s3, for bucket policies requiring encryption this results in the push failing and the following error message:

"ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied"

**Comment by akarve** [comment]
Hi. I am unable to reproduce this error. Would you post a full code sample and let us know how you've enabled encryption?

I have a Quilt stack running and switched on AES-256 encryption. Reads/writes of encrypted data continue to work. Is this possibly related to bucket policy, as suggested in the note in the following screenshot? 
![Screen Shot 2019-10-30 at 7 00 00 PM](https://user-images.githubusercontent.com/1322715/67912561-90142580-fb47-11e9-869b-70cbb9105f70.png)

**Comment by jdprusa** [comment]
I have default encryption with AES-256 enabled and am required to have a bucket a policy rejecting other types of encryption or non-encrypted PutObject Commands. It looks like this is a problem on my end and I'll work towards getting to solve, thank you.
