### ISSUE TITLE
Begging for `mutate=True` parameter on `fetch`

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#1327]
I was asked:

> "if i’ve already fetched a quilt package, how do i load it up to access it in python via quilt?"

Currently, `Package.fetch()` returns the subset of what the user just fetched, and only what they fetched, not in relation to the entire `Package` object.
```python
p = Package.browse("...", "s3://...")
local_files = p["images_2d"].fetch("some_dir")
# returns a `local package` object of just the files in directory `images_2d`
```

To get around this in I think the `t4` era, the following was possible:
```python
p = Package.browse("...", "s3://...")
# fetch and reassign
p["images_2d"] = p["images_2d"].fetch("some_dir")
# dump manifest to json so that it can be reloaded at a later time
p.dump("my_manifest.jsonl")
```

This is no longer possible (or was never possible and I am crazy) as `Package` objects do not have setters:
`TypeError: 'Package' object does not support item assignment`

My opinion here:
There needs to be a way to tell the `Package` object, I want to fetch this data but mutate the original object so that I have the full manifest still, just parts of it are local and parts of it are remote.
`p = p["images_2d"].fetch("some_dir", mutate=True)`, either mutate or add a setter to the `Package` object so that we can fetch and then assign.

This allows for people to continue to work with the full manifest through the `dump` and `load` operations, regardless of how many and which files are local or remote.

**Comment by akarve** [comment]
Wouldn't `.fetch` followed by `.browse` work for you? Once browsing the full manifest you could mutate the fetched data and then `p.set(DIR, MUTATED_DIR)`.

We have an API rev forthcoming that _should_ ease some of these issues. I will iterate with you on the same.

**Comment by JacksonMaxfield** [comment]
`.set` is for a single file. Would have to do `.set_dir` which loses the metadata for the entire directory. So the operation I believe would have to be something like the following pseudocode:
```python
p = Package.browse("...", "s3://...")

# Fetch and reassign to local package
local_files = p["images_2d"].fetch("some_dir")

# Loop through each downloaded file and set the file in the original package with metadata
for f in local_files:
    p.set(f"images_2d/{f}", local_files[f].get(), meta=p["images_2d"][f].meta)

# Original manifest is now mixed, local and remote
# Work with `p`
```

**Comment by akarve** [comment]
@JacksonMaxfield now that we have both local caching and subpackage install this Issue is fixed? Please close if so.

**Comment by JacksonMaxfield** [comment]
Yea I would say this is resolved. Thanks.
