### ISSUE TITLE
[Enhancement proposal] Add `is_logged` method

### ISSUE THREAD

**Issue by mjmikulski** [quiltdata/quilt#1514]
### Current status
Currently there is not any straightforward way to determine, if a user is logged in a private registry. As I observed, the login persists between sessions. Anyway, it would be nice to have this tiny method, for example to use in automated scripts.

### Proposition
Add `is_logged` method that would simply return a boolean.

**Comment by akarve** [comment]
@sir-sigurd let's add a method called "`logged_in()` that returns `True` or `False`.

**Comment by mjmikulski** [comment]
Perfect, thank you for your contributions! :)
