### ISSUE TITLE
importing a local package fails as `registry` now a required argument

### ISSUE THREAD

**Issue by knaaptime** [quiltdata/quilt#1522]
I'm trying to import [a local package](https://github.com/spatialucr/geosnap/blob/726718a74ffa077d950e9e38dea2b18b7ac267c7/geosnap/_data.py#L23) that gets created if it doesnt exist yet. 
after upgrading to version 3.1.10, I'm now getting

```
TypeError: _list_packages() missing 1 required positional argument: 'registry'
```

if i downgrade back to version 3.1.8, i can import my package successfully. I'm happy to change the call somehow, but it looks like  `_list_packages()` is private, so just wanted to check whether the change is intentional

**Comment by knaaptime** [comment]
[here's](https://travis-ci.org/knaaptime/geosnap/jobs/646097100?utm_medium=notification&utm_source=email) the trace on our CI in case its useful.

**Comment by akarve** [comment]
Hi Eli. 

Does your code call `_list_packages` directly? There should be a non `_` method that you can call. `_list_packages()` as you mention is private and I believe that we refactored for telemetry.

I looked at the trace and now wondering if you can point me to the source code of the unit test so that we can investigate?

**Comment by akarve** [comment]
Here is the public method and it appears to have a registry default:
https://docs.quiltdata.com/api-reference/api#list\_packages

**Comment by knaaptime** [comment]
thanks for taking a look! I'm  only trying to import a pacakge and not calling `_list_packages`. It's [this line](https://github.com/spatialucr/geosnap/blob/726718a74ffa077d950e9e38dea2b18b7ac267c7/geosnap/_data.py#L23)

I can recreate in a clean environment with quilt3 v3.1.10:

```python
# look for local storage and create if missing
try:
    from quilt3.data.geosnap_data import storage
except ImportError:
    storage = quilt3.Package()
```

raises

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-11b262dcd61d> in <module>
      1 # look for local storage and create if missing
      2 try:
----> 3     from quilt3.data.geosnap_data import storage
      4 except ImportError:
      5     storage = quilt3.Package()

~/anaconda3/envs/toss/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda3/envs/toss/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda3/envs/toss/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

~/anaconda3/envs/toss/lib/python3.7/site-packages/quilt3/imports.py in exec_module(cls, module)
     44
     45             # we do not know the name the user will ask for, so populate all valid names
---> 46             for pkg in _list_packages():
     47                 pkg_user, pkg_name = pkg.split('/')
     48                 if pkg_user == namespace:

TypeError: _list_packages() missing 1 required positional argument: 'registry'
```

**Comment by knaaptime** [comment]
it looks like [this line](https://github.com/quiltdata/quilt/blob/a764778d029713e235296b3c7d1e62f3678afcfd/api/python/quilt3/imports.py#L46) in imports.py is missing a `registry` argument?

**Comment by knaaptime** [comment]
there's a `registry` variable being created [on line 33](https://github.com/quiltdata/quilt/blob/a764778d029713e235296b3c7d1e62f3678afcfd/api/python/quilt3/imports.py#L33) so i'm guessing it just needs to be passed to `_list_packages()`?

**Comment by knaaptime** [comment]
just checking back to see if this issue is affecting anyone else? I'm still stuck on version 3.1.8 otherwise i cant import local packages

**Comment by akarve** [comment]
@cosmic-byte is investigating

**Comment by akarve** [comment]
Should be fixed in https://github.com/quiltdata/quilt/pull/1537 - would you like to try it out?

**Comment by knaaptime** [comment]
yep, i think that does the trick. thanks!
