### ISSUE TITLE
Please provide option to not see progress bars on download/hash/etc.

### ISSUE THREAD

**Issue by gdesmarais-ctx** [quiltdata/quilt#1559]
tqdm is nice on a console, but messes up log files, especially CloudWatch.  An option to turn it off would be helpful, or even an automatic detection when running in AWS.  I happen to use it in Batch, so I look for `os.environ.get("AWS_BATCH_JOB_ID")`.

**Comment by akarve** [comment]
How would you like that option to maniefst, as an environment variable (e.g. `QUILT_USE_TQDM=''`)? I'm a bit leary of automagic detection of batch, though we'll consider it.

**Comment by gdesmarais-ctx** [comment]
Sure, an env var is reasonable, and I totally understand the batch issue. The only other place I can think of is the api, which would get ugly and is probably not nice oo.

**Comment by akarve** [comment]
Fixed in the upcoming PyPI release.

**Comment by akarve** [comment]
Docs here https://docs.quiltdata.com/references/faq#can-i-turn-off-progress-bars-for-log-files
