### ISSUE TITLE
`list_package` and `list_package versions` return a generator object

### ISSUE THREAD

**Issue by knaaptime** [quiltdata/quilt#1576]
instead of listing the packages/versions from a given registry, these functions return a generator object

```python
import quilt3
quilt3.list_packages()
```
returns
```
<generator object _list_package_versions at 0x115650b50>
```

the same happens if an explicit registry is passed

**Comment by akarve** [comment]
Yeah, this is actually correct behavior now. It's for performance reasons. but we should have bumped the semver higher for this so our bad.

You can either iterate the generator or (worse for perf on large registries) `list(quilt3.list_packages())` to unroll it.

**Comment by knaaptime** [comment]
got it, thanks! I'm still having some weird issues using local packages, though. For instance

![image](https://user-images.githubusercontent.com/4213368/77580190-cbb5e000-6e98-11ea-8af2-22f0bff65825.png)

**Comment by akarve** [comment]
This is fixed in #1560 - if you want try it please do. Will release.

**Comment by akarve** [comment]
Oh and a workaround for this (import, for reasons not entirely in our control) can be flaky:
quilt3.Package.browse("census/administrative")

**Comment by knaaptime** [comment]
dope, thank you
