### ISSUE TITLE
Build destination should default to user home and read from an environment variable

### ISSUE THREAD

**Issue by akarve** [quiltdata/quilt#164]
Suggest `QUILT_BUILD_PATH`as env vars. See #1 for details.

**Comment by stillmatic** [comment]
Would this supersede the current folder search logic (i.e. search in current folder and all above)?

**Comment by akarve** [comment]
We were discussing this today. Concluded that we shouldn't mess with "look in parent" logic for module resolution?

I updated this issue to only affect where `quilt build` writes the package to, as we've seen users build a package in a random directory and then not be able to import it.

@stillmatic What do you think?

**Comment by stillmatic** [comment]
I think that makes sense and resolves a pain point I had while writing the R package. I had to create a random temp directory (https://github.com/stillmatic/quiltr/blob/master/R/build.R#L28) to ephemerally dump the changed files. This method 'works' but is definitely suboptimal.

Having a fixed `QUILT_BUILD_PATH` would make that part easier. How would you deal with collisions?

**Comment by akarve** [comment]
Collisions would overwrite (as we have today). Any pushed packages are of course tracked by `quilt log` and users can revert with `quilt install`.

**Comment by akarve** [comment]
OK this turns out to be nontrivial with unforseen effects on push and install--as I discovered when testing a "quick fix". We're going to need a more comprehensive fix--likely in the spirit of Docker where there's flat repository for all builds. I'm working on it. CC @salvor7

**Comment by akarve** [comment]
Fixed by new store implementation
