### ISSUE TITLE
DataNode and GroupNode should give access to original names

### ISSUE THREAD

**Issue by diwu1989** [quiltdata/quilt#166]
`DataNode` should be extended to allow access to the original file name via a `.name` property

It doesn't seem possible to get back the extension of the original file otherwise, and extensions matter for video files.

the `metadata` in the json file seem to already have this information

**Comment by diwu1989** [comment]
The same goes for `GroupNode`, should be storing the original folder name.
This way I can easily write a `export` command that take a quilt package and restore it back 1:1 to the folder hierarchy that it came from.

**Comment by akarve** [comment]
This feature will be handled in #495 and is partially implemented in the existing `quilt export feature`. Closing as duplicate.
