### ISSUE TITLE
Catalog failing to render thumbnails on package view but succeeding on file view

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#1791]
File view thumbnails load just fine: https://open.quiltdata.com/b/allencell/tree/aics/actk/master/singlecellimages/cell_images_3d/
Package view thumbnails fail to load: https://open.quiltdata.com/b/allencell/packages/aics/actk/tree/latest/master/singlecellimages/cell_images_3d/

I would assume this has to do with the recent 3.2.0 release regarding package view?

**Comment by akarve** [comment]
That's really interesting. We haven't actually touched the code on open for a few weeks and 3.2 wouldn't affect it. Imma file this as a bug in our backlog.

**Comment by nl0** [comment]
should be fixed in #1806
