### ISSUE TITLE
Catalog does not render large Vega JSON files (created by altair)

### ISSUE THREAD

**Issue by ltirrell** [quiltdata/quilt#1820]
## Summary
When running a local `quilt3 catalog`, large Vega JSON files (created using `altair`) are not rendered. They just appear as rendered text. Small Vega JSON files do show up as interactive charts within the localhost catalog (I added an [example file from an open quilt dataset](https://open.quiltdata.com/b/quilt-covid-19/tree/innovation/directory/map.json) to a Package and could view it locally).

JSON files were created with a pattern like:
```python
with open("file.json", "w") as f:
    f.write(altair_chart.to_json())
```
or `altair_chart.save('file.json)`. Both ways led to the same results

An example large JSON (~12 MB) was sent to Aneesh over slack. I could send or upload this in a different way if you like. 

## Software versions:
- Python packages
  - `quilt3==3.2.0`
  - `altair=='4.1.0'`
- Docker image (the current latest): 
  - `quiltdata/catalog@sha256:32e3bb5c33b61f78de7cb2dfb774173cc3e9b9a9d1eb72365b25c12e3632548e`
- Vega Lite schema (within the JSON file):
  - `"$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json"`

**Comment by akarve** [comment]
We will be upping the file size limit (for Vega previews) in an upcoming release to resolve this issue.

**Comment by akarve** [comment]
Resolved in https://github.com/quiltdata/quilt/pull/1873
