### ISSUE TITLE
Cannot retrieve the old version data

### ISSUE THREAD

**Issue by highfly22** [quiltdata/quilt#3142]
I try to get the file content from old version. But quilte3 always return the latest file.

Steps to reproduce:

```
Package.set('a')
Package,push()
# modify the file named 'a'
Package.set('a')
Package,push()
Package.browser('repo/repo', "s3://quilt", "oldversion_hash")
Package['a'].get_bytes() return old data

```
I have enable versioning in the bucket s3://quilt.

How to get the file of old version?

**Comment by sir-sigurd** [comment]
I can't reproduce this.

You could check where objects were put for both previous and last revisions of package:
`str(quilt3.Package.browse('test/test', registry="s3://quilt")["a"].physical_key)` and compare version ids of objects and compare contents of versions.

(also your steps to reproduce doesn't seem be working and complete)

**Comment by drernie** [comment]
Can not reproduce.
