### ISSUE TITLE
Quilt 2.9.15 within AWS Lambda execution

### ISSUE THREAD

**Issue by LanzaTyler** [quiltdata/quilt#3344]
## Summary
I have code I'm attempting to run in an AWS Lambda function (python 3.7 docker image) and one of its dependencies requires quilt 2.9.15. I see the docs for latest [suggest setting XDG_CACHE_HOME to `/tmp/...`](https://docs.quiltdata.com/api-reference/cli#xdg_) to support Lambda execution. I did that, but the suggestion isn't present in the '2' version of the docs so I'm not sure if it's relevant. 

My error is as follows and it persists after setting XDG_CACHE_HOME:
```json
{
  "errorMessage": "Package equilibrator/cache not found.",
  "errorType": "CommandException",
  "requestId": "",
  "stackTrace": [
    "(... my code ...)",
    "  File \"/var/task/conda/lib/python3.7/site-packages/equilibrator_api/__init__.py\", line 38, in <module>\n    ccache = create_compound_cache_from_quilt()\n",
    "  File \"/var/task/conda/lib/python3.7/site-packages/equilibrator_cache/api.py\", line 79, in create_compound_cache_from_quilt\n    cache = quilt.load(package)\n",
    "  File \"/var/task/conda/lib/python3.7/site-packages/quilt/tools/command.py\", line 1355, in load\n    node, pkgroot, info = _load(pkginfo, hash)\n",
    "  File \"/var/task/conda/lib/python3.7/site-packages/quilt/tools/command.py\", line 1346, in _load\n    raise CommandException(\"Package {package} not found.\".format(package=package))\n"
  ]
}
```

The kicker is that the same code works locally with the same inputs using `awslambdaric` as the entrypoint: 
```dockerfile
RUN mkdir -p ${FUNCTION_DIR}/.aws-lambda-rie && curl -Lo ${FUNCTION_DIR}/.aws-lambda-rie/aws-lambda-rie \
    https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie \
    && chmod +x ${FUNCTION_DIR}/.aws-lambda-rie/aws-lambda-rie
ENTRYPOINT [ "/var/task/.aws-lambda-rie/aws-lambda-rie", "python3", "-m", "awslambdaric" ]
``` 
### Troubleshooting attempts

If I exec into my docker image and check the value of XDG_CACHE_PATH, it is what I set: 
```bash
bash-4.2# echo $XDG_CACHE_HOME
/var/task/quilt
```
I made sure to set its value before import of quilt. 

I also confirmed that the quilt package is installed: 
```bash
bash-4.2# quilt install equilibrator/cache
Downloading package metadata...
equilibrator/cache already installed.
Overwrite? (y/n)
```

I tried adding a `RUN quilt install cache` to my dockerfile just to see if it would reset something, but it hangs waiting for y/n and there doesn't seem to be support for a -y flag (?). 

I also tried adding quilt3 as an explicit dependency `quilt3[pyarrow]` for my project, but it didn't seem to have any effect, probably because its name is 'quilt3' and not 'quilt'.
![image](https://user-images.githubusercontent.com/101131242/220990951-ec8c6b79-e1b3-4834-8d46-adc34ff21a66.png)

### Additional context 
I am using a multi-stage dockerbuild with the first stage from `AmazonLinux2` and the second stage from `public.ecr.aws/lambda/python:3.7`. This allows me to install all of my required pip wheels in stage 1 and copy the wheels directory to stage 2 for final installation. The goal is to avoid platform discrepancies / specifying platform every time. (I have no idea if this is related to the problem).    

## Questions
1. Is this problem actually related to cache location, or is something else potentially to blame here? Maybe I need to set something like a quilt PATH variable?
2. If the problem is the cache location, is there a different solution for quilt 2.9.15? 

The fact that the code executes locally is probably a big hint. Maybe there's some _other_ files outside of /tmp that get wiped in the live environment? 🤔 Thank you for any help you can provide!

**Comment by LanzaTyler** [comment]
I tried a find command in my local instance and realized that my quilt package was installed under /root
![image](https://user-images.githubusercontent.com/101131242/221209546-1141d597-2b35-4855-be6b-66ef9d8d442d.png)
Based on [this issue](https://github.com/quiltdata/quilt/issues/621), it looks like I can do the following to fix this:
```dockerfile
ENV QUILT_PRIMARY_PACKAGE_DIR="/var/task/quilt/quilt_packages"
```
Will report back! 🤞

**Comment by akarve** [comment]
Hi, quick note here that `quilt3` is under active development whereas `quilt` is not. We strongly recommend `quilt3` for all production workflows. Do you know the maintainer of the package you are working with?

**Comment by LanzaTyler** [comment]
@akarve We have old forks of the equilibrator repos that we use. It looks like the original repos no longer use quilt, so I'll add an issue on ours to either upgrade quilt or get a fresh fork. I agree that we should not be using this outdated of a version. 

The good news is that setting that env variable worked! So my issue is resolved. Thank you!
