### ISSUE TITLE
Issues with the Registry folder contents

### ISSUE THREAD

**Issue by palacima** [quiltdata/quilt#342]
- Server Error is returned when trying to push a data repo in the local test environment

- After login, navigating to localhost:3000 and clicking log in on the UI, it creates an infinite loop between http://localhost:3000/profile and http://localhost:3000/oauth

- On the Dev Environment setup for Ubuntu 16.04.3 on step 4, there is a file referenced that does not exist on the most up-to-date branch
`source quilt_server/flask_dev.sh`

Has anyone else noticed these issues or have solutions available?  Would like to create a private hub to store sensitive data via docker and s3 but have been unable to work around these issues

**Comment by kevinemoore** [comment]
We've seen that behavior with an older version of the identity service.

Can you try re-pulling quiltdata/django (the identity server) image from Docker Hub? The latest version has hash: 0e63f815fca589c5c93cd811a2f61be2c3d2b39aa130557fc9e3dc4e38f22a69

**Comment by akarve** [comment]
Hi @palacima, `docker-compose up` on master is working for me.  I updated Django with `docker pull quiltdata/django`. Below is the relevant output from `docker images`. If you don't see the right image IDs for catalog and flask, you can try `docker-compose build flask catalog`.

Let us know if that works for you. Note that running the registry with `docker-compose` is for testing purposes only in that, by default, packages do not persist across database invocations.

```
dockerapk-mbp-3:registry karve$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
quiltdata/django           latest              85d899695c25        3 hours ago         861MB
quiltdata/catalog          latest              7f44792550f5        4 hours ago         597MB
quiltdata/flask            latest              0ff1dcfccfad        4 hours ago         527MB
```

**Comment by palacima** [comment]
Sorry for the late response, these solutions worked. Thanks!
