### ISSUE TITLE
Update quilt docs with self-hosting a quilt registry

### ISSUE THREAD

**Issue by AlexGoico** [quiltdata/quilt#371]
My first impressions from https://docs.quiltdata.com/ are that there are no self-hosting options since I don't see anything about quilt config or the information in https://github.com/quiltdata/quilt/tree/master/registry. So perhaps it could be updated to reflect instructions about self-hosting from the README docs in quilt/registry.

**Comment by akarve** [comment]
Thanks @AlexGoico. I've started to address this issue in https://github.com/quiltdata/quilt/pull/374. We don't yet have explicit deployment instructions. I've backlogged the same as #375.

**Comment by akarve** [comment]
@AlexGoico further feedback welcome. The new docs should be live at https://docs.quiltdata.com/ once gitbook picks up the changes.
