### ISSUE TITLE
Summary Stats for Packages

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#427]
A majority of my packages are quite large so the largest desire is for there to be at least an indication of package size before install on the Quilt registry page.

If this is the current package stats area:
```
Latest update

date
    1/10/2018, 2:07:10 PM
author
    @aicsjackson
version
    2aed0783417118de00913d2ffe7be9968c881eb990993d6f5fdb957d0f49354
```

Would be nice to also see items like:
```
Latest update

date
    1/10/2018, 2:07:10 PM
author
    @aicsjackson
version
    2aed0783417118de00913d2ffe7be9968c881eb990993d6f5fdb957d0f49354
size
    200 GB
files
    tiff | 400
    json | 1600
```

Would allow for better insight into the package contents prior to downloading.

**Comment by akarve** [comment]
@dimaryaz would you add `size` and `leaf_node_count` to `/api/package_preview`?
@JacksonMaxfield counting file types is a bit tricky since some nodes (e.g. in-memory data frames pushed into a package) don't have types.

**Comment by akarve** [comment]
Actually, if possible let's do `size` (total package size) and a dict of file_types (deuced from `q_ext`). I guess we can have `__NO_EXT__` key or something like that for pure dataframes or weird files without a `.EXT`.

**Comment by akarve** [comment]
Sizes are live in production. File types are next. Example: https://quiltdata.com/package/aicsjackson/prod/

**Comment by akarve** [comment]
Complete as of  `master` 6933bab. Will be released to production in next release.
