### ISSUE TITLE
Package Creator Detailed Stats

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#463]
Great work on the summary stats for packages!

I also realized it would be neat to see more detailed insight into my own package data. On the user settings page, a user can see all of their packages in a list. If next to each package name there were details on number of downloads, maybe some sorting mechanism, so instead of seeing the list in alphabetical order, I can order by most or least downloaded. Peak traffic to the package page + peak traffic to download the data? Etc.

**Comment by JacksonMaxfield** [comment]
Any update on this @akarve?

**Comment by akarve** [comment]
Yes. The endpoints to track downloads are in place (as part of the teams codebase). Next we need to expose them in the frontend. I anticipate starting the frontend work in the next 1-2 weeks.

**Comment by akarve** [comment]
Superseded by Quilt 3 and handled on Bucket Overview page, Detail page, Package stats.
