### ISSUE TITLE
Automate splitting datasets into training, test and validation sets for ML in build

### ISSUE THREAD

**Issue by kevinemoore** [quiltdata/quilt#467]
For data packages used in machine learning, it would be useful for Quilt build to support splitting inputs into fixed sets for model training, and validation. For structured data, the various sets (training, test and validation) could be children of a common parent so that the entire dataset is available (by calling _data on the parent). Thanks to @rhiever for the suggestion.

**Comment by rhiever** [comment]
Great! It could also be useful to specify k-fold cross-validation splits.

This diagram shows a fairly standard training-validation-test split:

![image](https://user-images.githubusercontent.com/1719223/37048546-0c3a82ea-2123-11e8-9f90-64e6e065e515.png)

and this diagram shows k-fold cross-validation splits:

![image](https://user-images.githubusercontent.com/1719223/37048571-1def85b2-2123-11e8-9c72-80dc35cc28bf.png)

If k-fold cross-validation is used, typically the "training" and "validation" splits from the first diagram are combined into just the "training" split (leaving only the "training" and "test" splits), and the "training" split is then divided into the k-fold cross-validation splits.

**Comment by akarve** [comment]
Quilt 3, combined with PyTorch or TF APIs, now allows direct interaction with file system and provides primitives for arbitrary file organization.
