### ISSUE TITLE
Make All Children Nodes Subscriptable

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#474]
Currently GroupNodes and DataNodes are callable only by attribute. With an executable function attached if you want the actual data.

```python
from quilt.data.aics import prod

# retrieves the image load node
print(prod.fovs.unique_fov.image.load)

# retrieves the image load node file path
print(prod.fovs.unique_fov.image.load())
```

This current implementation is great. However it would also be nice to traverse nodes as dict-like.

```python
from quilt.data.aics import prod

# retrieves the image load node
print(prod['fovs']['unique_fov']['image']['load'])

# retrieves the image load node file path
print(prod['fovs']['unique_fov']['image']['load']())
```

**Comment by akarve** [comment]
Agreed that we need at least subscripting. There is a semi-involved refactor required to get to this (because we want to completely change how package nodes are retrieved, and make it much more flesible) so it may take us a while to tackle this but it is on the roadmap.

**Comment by JacksonMaxfield** [comment]
As an intermediate step for the subscriptable behavior, and before the navigation rework, can something like be implemented.

```python
def getnode(self,key):
   return getattr(self, key)

quilt.nodes.Node.__getitem__ = getnode

# now this works
pkg['node']
```

? Don't know if this would break other packages but it seemingly works from small internal testing.

**Comment by akarve** [comment]
Available in Quilt 3
