### ISSUE TITLE
Pretty Printing Group Nodes

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#493]
Currently, when I: `print(pkg.group_node)`
I am returned something like this:
```json
<GroupNode>
node_0
node_1
node_2
node_3
node_4
node_5
node_6
node_7
node_8
node_9
```
Where every sub-node is printed.

However, for packages like mine, it isn't uncommon to have hundreds of nodes nested under each other and thus this printing structure isn't the best for viewing.

Two options in my mind:

When I print a group node, have it print a structure like that of the contents section of the webpage preview of a package.
`print(pkg.group_node)`
Would return:
```json
<GroupNode>
node_0
   subnode_0
      subsubnode_0
      subsubnode_1
   subnode_1
      subsubnode_0
      subsubnode_1
   ...
node_1
   subnode_0
      subsubnode_0
      subsubnode_1
   subnode_1
      subsubnode_0
      subsubnode_1
   ...
...
```

Or have it print first n and last n subnodes of the node.
`print(pkg.group_node)`
Would return:
```json
<GroupNode>
node_0
node_1
node_2
...
node_n-2
node_n-1
node_n
```

Maybe implement both and have a `quilt.set_prints('show_depth')` / `quilt.set_prints('show_length')` to indicate which printing method the user wants.

**Comment by akarve** [comment]
@JacksonMaxfield does #515 solve this issue?

**Comment by akarve** [comment]
Reopening until we resolve some issues with #515
