### ISSUE TITLE
Specified Area in DataNode Class for Custom Load Functions

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#496]
While supporting dataframes as first class objects, and I have heard rumors of json -> dict and npz -> ndarray are excellent to have. There are all sorts of files that would be hard to support as first class in-memory solutions but would be great to have a standard loading mechanism.

If in the DataNode class there was a simple solution for community members to add/ edit standard loading functions that would be a great addition.

```python
class DataNode():
   # put your functions here community
   def json(self):
      import json
      return json.load(self())

   def tiff(self):
      import tifffile
      return new tifffile.TiffFile(self())
```

This would now make it so that the below functionality may work.
```python
# current behaviour
print(pkg.data_node())
'/quilt_packages/objs/lkjh21398123jknloaisjdfp81jhiuqsdf'

# json behaviour
print(pkg.data_node.json())
{'hello': 'world', 'foo': 'bar'}

# tiff behaviour
print(pkg.data_node.tiff())
<TiffFile object>
```

So while having first class support for certain types of objects that can live in memory easily, dataframes, ndarrays, dict, etc. rare file types would have pseudo first class support through helper functions.

**Comment by akarve** [comment]
Closing as Quilt 2 issue. Please refile against Quilt 3 as needed.
