### ISSUE TITLE
Package List Filter

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#498]
As I am an odd use case and I make 20000 packages to build a single package in some cases, I know this is an odd request. However would be great to have some sort of filtering options put on the `quilt.ls()` function.

```python
# return only packages created under the namespace 'aics'
quilt.ls(owner='aics')

# return all packages that begin with the word 'cell'
quilt.ls(grep='cell*')
```

**Comment by akarve** [comment]
Once we return real Python data structures from the API, `filter` and comprehensions will just work.
