### ISSUE TITLE
Searching Doesn't Allow Term Chaining

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#512]
The current implementation of searching, at least from what I can tell, doesn't allow term chaining.

If I search for `myosin`, I get the following results back:
<img width="797" alt="screen shot 2018-03-21 at 3 53 42 pm" src="https://user-images.githubusercontent.com/17132317/37741795-154f57bc-2d20-11e8-80c2-0b37d37e3fc5.png">

These are correct results, however if I wanted to search for differing sets of data with a single search, I cannot. Example being: maybe I am interested in both `myosin` and `junctions` so I search `myosin junctions` (note these terms don't really relate, but results for either `myosin` or `junctions` should return in my opinion)

I am returned results that only contain them both, not the individual lines.
<img width="758" alt="screen shot 2018-03-21 at 3 55 54 pm" src="https://user-images.githubusercontent.com/17132317/37741926-aada22ee-2d20-11e8-9b4e-6b46b537c639.png">

To my understanding this is because all search terms must not only all be in the README, node names, package name, etc. But all the search terms must be in the direct order they are given in.

As seen here. I know `myosin` is in the `aics/random_sample` package, so I search for `random myosin`.
<img width="702" alt="screen shot 2018-03-21 at 4 00 08 pm" src="https://user-images.githubusercontent.com/17132317/37741990-f7a6c79e-2d20-11e8-910a-b5bd07922204.png">

`random` is in the name of the package, and `myosin` is labeled as a keyword in the README, but because they are not directly ordered like the search, the package `aics/random_sample` is not returned.

I haven't looked into ts_vector too much but I would believe that ts_vector is per-word not per-document. In which case I think this is an issue of breaking down the search into individual terms?

**Comment by akarve** [comment]
+ @dimaryaz for comment

**Comment by dimaryaz** [comment]
Thanks for pointing this out; that's pretty major bug. What's happening is: originally, we had a really basic search that only matched substrings of package owner and name. Then I added full-text search of READMEs, but to keep the original search working, I made it return packages where (owner+name matches the query) OR (README matches the query). Of course, that means, keywords can't be split up between owner+name and README.

Would this explain everything you're seeing? As far as I can tell, order doesn't actually matter. Also, not sure what term chaining means.

**Comment by akarve** [comment]
It looks like the eventual fix for this will be one index for everything. as yet unclear how we tokenize package names like `dogscats` so that they match on both `dog` and `cat` since `dogscats` is not a dictionary word. does anyone know of a stemming or dictionary library we can use for this?

**Comment by JacksonMaxfield** [comment]
@dimaryaz You are correct, order doesn't matter. Don't know why I originally thought that. By term chaining I meant that I couldn't search for multiple things that may not be related, i.e. the myosin junctions, two separate terms that should produce different packages but return nothing.

@akarve stemming and dictionary libraries are usually expensive (but maybe I am just bad at implementing them), the solution I use when doing these types of computations is to multiply the `ts_vector` (or whatever word ranking system you are using) by the Levenshtein distance of the search term from the found term divided by length of whichever term is longer as a sort of relevancy check. In your `dogscats` example, both `dog` and `cat` would both return `ts_vector * 5/8`. Maybe that would work here too? Still need to figure out how `ts_vector` works though so this solution may not be relevant.

**Comment by JacksonMaxfield** [comment]
Ignore above Levenshtein distance comment, I don't think it works with `ts_vector` computations. My implementation focuses on the detecting the relevancy of text from a search while ts_vector just detects if the words are present in a set of texts I think?

**Comment by dimaryaz** [comment]
It is now fixed!

![screenshot from 2018-04-05 11-51-58](https://user-images.githubusercontent.com/4365877/38385852-db692614-38c7-11e8-8e18-16e453906cb6.png)

Let me know if anything else looks wrong.
