### ISSUE TITLE
Add `_parent_node_` Attribute to GroupNode and DataNode Objects

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#514]
Would allow people to build custom navigation functions that traverse the package tree for them.

Example:
```python
def get_associate(node):
    # return the parent of parent other associated node
    return node._parent_node_._parent_node_.sub_node_1.data

node = dataset.initial.sub_node_0.data
associate = get_associate(node)
```

This is a simple example, but allowing this functionality means we can write very detailed custom navigation functions if we wanted to add more parameters and such to determine which associate to go to, etc.

I will try to dig through the GroupNode and DataNode creation code and add the attribute unless someone else gets it first.

**Comment by akarve** [comment]
Superseded by Quilt 3
