### ISSUE TITLE
Linked Data (RDFa, JSON-LD)

### ISSUE THREAD

**Issue by westurner** [quiltdata/quilt#542]
These datasets would be even more discoverable if at least their metadata were described with Linked Data.

- https://schema.org/DataCatalog
- https://schema.org/Dataset
  - https://schema.org/Dataset#examples

Here's an example of adding RDFa to an HTML page (and links to background info and validators for Schema.org, OpenGraph, and Twitter Cards structured data):
https://github.com/CodeForAntarctica/codeforantarctica.github.io/pull/3

There's a lot of linked open data. Here's a view of the LODCloud:

http://lod-cloud.net

****
This should maybe be another issue.

If we have URIs for column names, datatypes, and physical units (also accuracy and precision), we can find and compare and maybe even concatenate datasets.

- subject: http://dataset_uri/#columnname
- name/label: "Column Name"@en
- datatypes: XSD URIs
- physical units:
  - QUDT
  - https://schema.org/StructuredValue

I think what is needed are dataset headers that map this metadata onto columns in existing formats. CSVW (CSV on the Web) is built on the Tabular Data Model; which specify how this metadata can be expressed as JSONLD (and thus any RDF representation).

SPARQL is one query language for linked data.

I wrote up a bunch of this background information in pandas-dev/pandas#3402 "ENH: Linked Datasets (RDF)". And mentioned the opportunity for CSVW-like headers in Arrow and Parquet to @wesm on Twitter awhile back.

- [ ] Dataset metadata on dataset HTML pages
- [ ] Dataset column metadata across the ecosystem

**Comment by akarve** [comment]
Interesting and could be extremely useful. After the upcoming API (and metadata) refactor, the registry will have comprehensive metadata for each package (generated by the compiler). We can then provide a metadata endpoint (consumable by the JavaScript catalog) and then project that data into the above formats.

@westurner is this something you'd be interested (after the metadata refactor in ~2weeks) in implementing? [Quilt Slack](https://slack.quiltdata.com/) is a good place to discuss. We can help navigate you around the rough edges. Compilation lifecycle needs a refactor too and having consumers of the API will motivate us to do that faster :)

**Comment by westurner** [comment]
Here's what will be needed after the metadata refactor in order to accomplish task 1:

- [ ] Dataset metadata on dataset HTML pages

- [ ] a link to the dataset template source
- [ ] a link to the dataset data model
- [ ] instructions for how to test locally
   (because the HTML/RDFa output needs to validate with any/all of the validation tools liked in the codeforantarctica PR linked above)
- [ ] a reminder/notification @westurner when the refactor is sufficiently complete

**Comment by akarve** [comment]
Quilt 3 now includes JSON-LD sufficient for Google Dataset Search

**Comment by westurner** [comment]
Thanks!
