### ISSUE TITLE
does quilt supports HDFS big data and Spark (pySpark)?

### ISSUE THREAD

**Issue by chanansh** [quiltdata/quilt#563]
It's not clear from the documentation

**Comment by kevinemoore** [comment]
Thanks for the question! Quilt supports reading packages in pySpark. Structured datasets are read into Spark DataFrames. In Spark, most often, you'll want to access a large partitioned table as a Spark DataFrame by accessing the GroupNode and calling _data() (or just calling the object()). There's no support in Quilt yet for distributed package creation (build) in pySpark. Is that something you would find useful?

Quilt doesn't yet support running a separate registry on HDFS, but that's definitely on the roadmap.

**Comment by chanansh** [comment]
I am not sure I understand the terminology of build and call. I will read
your documentation. Essentially I have ~1Tb HDFS data which changes from
time to time and I would like to manage it's versions. Currently I just use
folders with date and set a string in the code to point to the relevant
path. Can quilt help me?

**Comment by kevinemoore** [comment]
@chanansh, `build` is a Quilt command that creates a new snapshot of your data (as a new package version). By `call` I simply meant the Python `__call__` method, which is callable by just adding () to a node in the Quilt package.

My guess is that Quilt will need a couple of small extensions (which are all on the roadmap) before it will do what you want. Basically, we'll need to add support for using HDFS in a PackageStore. That could be as easy as swapping the normal Python os.path and pathlib calls for hdfs3 when using HDFS and pyspark.

What type of data are you storing in HDFS? Parquet files?

**Comment by kevinemoore** [comment]
Great! And, is it a set of partitioned tables? We just added support for Parquet input data, but the code doesn't handle partitioned tables/dataframes yet. I can probably get a prototype of that working this afternoon if you'd like to give it a try.

**Comment by chanansh** [comment]
Partioned . Thanks anyway.

**Comment by leferrad** [comment]
I'm also interested on loading and versioning data from HDFS through Quilt, so it can be integrated on a Spark pipeline of distributed data processing. Can someone give me details of this integration Quilt + HDFS? is it feasible? Thanks!

**Comment by akarve** [comment]
Current support is for S3 and S3 connectors can be used to provide access via Hadoop. General trend is away from HDFS towards S3. Feel free to reopen if still an issue.
