### ISSUE TITLE
`quilt rm` appears to succeed on non-existent package

### ISSUE THREAD

**Issue by ykarbaschi** [quiltdata/quilt#586]

**Comment by akarve** [comment]
A few issues to tackle:
* We should print an err message if user tries to delete a package that doesn't exist.
* `TableNode` in core.py has some bugs: first the `assert PackageFormat...` will blow up if the user has a store with old (HDF5) packages. This is rare but the error message should be better and ideally should name the offending package.

**Comment by eode** [comment]
Moved TableNode issue to a separate bug.
