### ISSUE TITLE
pyarrow is not support win32 or win64, so quilt is the same ?

### ISSUE THREAD

**Issue by orangeSi** [quiltdata/quilt#618]
Hi, 
    When I pip install quilt in win7,   quilt need pyarrow<0.8.0,>=0.4.0, but pyarrow seems only support linux/mac/win-amd, but my computer is intel-win64~

help!

thanks~
Si

**Comment by meffij** [comment]
@orangeSi What is your Python version? [This documentation](https://arrow.apache.org/docs/python/install.html) says pyarrow is only available on Windows for Python 3.5 and above. If you have multiple Python installations, make sure you're using the pip that corresponds to your python 3 installation. On some of my machines, python and pip are python 2, and python3 and pip3 are python 3.

I hope this helps! If not, please don't hesitate to follow up here.

**Comment by orangeSi** [comment]
my python is 3.6,i will check the version of pip, thanks!

**Comment by akarve** [comment]
@orangeSi any updates?

**Comment by orangeSi** [comment]
`source activate geoplot ; pip -V` output this:
  pip 10.0.1 from D:\install\conda\envs\geoplot\lib\site-packages\pip (python 3.6)

`pip install quilt` output this:

 Collecting quilt
  Downloading https://files.pythonhosted.org/packages/62/99/7b16a2b36d8bcb01a336a7f2ca3a37095fd2f64c907b98c85af3cf0e1ad4/quilt-2.9.5-py3-none-any.whl (98kB)
Requirement already satisfied: requests>=2.12.4 in d:\install\conda\envs\geoplot\lib\site-packages (from quilt) (2.18.4)
Requirement already satisfied: six>=1.10.0 in d:\install\conda\envs\geoplot\lib\site-packages (from quilt) (1.11.0)
Collecting pyyaml>=3.12 (from quilt)
Collecting appdirs>=1.4.0 (from quilt)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting future>=0.16.0 (from quilt)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting packaging>=16.8 (from quilt)
  Using cached https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.19.2 in d:\install\conda\envs\geoplot\lib\site-packages (from quilt) (0.22.0)
Collecting xlrd>=1.0.0 (from quilt)
  Using cached https://files.pythonhosted.org/packages/07/e6/e95c4eec6221bfd8528bcc4ea252a850bffcc4be88ebc367e23a1a84b0bb/xlrd-1.1.0-py2.py3-none-any.whl
Collecting pyarrow<0.8.0,>=0.4.0 (from quilt)
  Could not find a version that satisfies the requirement pyarrow<0.8.0,>=0.4.0 (from quilt) (from versions: 0.9.0)
No matching distribution found for pyarrow<0.8.0,>=0.4.0 (from quilt)

**Comment by orangeSi** [comment]
sorry，maybe I know what‘s wrong. Pyarrow need win-64, but my python or conda maybe is win-32, So the installation of conda install pyarrow failed.

**Comment by orangeSi** [comment]
thanks~
Si
