### ISSUE TITLE
Basic question: how to configure where packages are locally stored?

### ISSUE THREAD

**Issue by butala** [quiltdata/quilt#621]
I apologize for asking such a basic question, but I cannot find an answer in the docs or via `quilt help`.

I digging around the Allen Cell Explorer dataset, and it is rather large. On my mac laptop, packages are stored at `~/Library/Application Support/QuiltCl`. I want to instead use a path on an external drive with plenty of space. 

Is there an environment variable I am missing? `quilt config` seemed promising, but I do not think my answer is there either.

--- Mark

**Comment by dimaryaz** [comment]
You can set a `QUILT_PRIMARY_PACKAGE_DIR` environment variable; see examples here: https://docs.quiltdata.com/shared-store.html

Note that the directory has to be named "quilt_packages".

**Comment by butala** [comment]
That worked perfectly. Thank you @dimaryaz!
