### ISSUE TITLE
Link images in package readme

### ISSUE THREAD

**Issue by guenp** [quiltdata/quilt#641]
It would be great to be able to link images and/or other files in the package in the readme such that they show up in the UI.

Inspiration: https://bl.ocks.org/mbostock/b2fee5dae98555cf78c9e4c5074b87c3

**Comment by akarve** [comment]
Hi @guenp. We currently allow users to link images, here is [an example](https://quiltdata.com/package/weiji14/nz_space_challenge). Is this what you had in mind?

In the README it looks like this:
```
![Minion](https://octodex.github.com/images/minion.png)
```

**Comment by akarve** [comment]
Ah, now I understand that you wish to link images or files from within the package. We don't support that just yet. I will leave this issue open until we do :)

**Comment by akarve** [comment]
Now supported
