### ISSUE TITLE
Provide truncated view of data from package overview page

### ISSUE THREAD

**Issue by flyinactor91** [quiltdata/quilt#675]
Currently, the only ways to see an example row of data are by downloading the package or if the maintainer provided an example in the description. There should be a way to view the head of tabular data from the package file tree or similar mechanism.

It could be a new page that displays df.head(n) for tabular data. Unstructured data could be loaded as-is if below a certain file size.

**Comment by akarve** [comment]
Quilt 3 now supports previews of data via the catalog. Clients can virtualize data via appropriate file formats for byte seeks to S3.
