### ISSUE TITLE
Inspect a particular version

### ISSUE THREAD

**Issue by hunan-rostomyan** [quiltdata/quilt#685]
Could be useful to be able to inspect the contents of a package at a particular point in time, say by passing the hash:

```
quilt inspect [USER]/[PKG] --hash [HASH]
```

More concretely:

I have a bunch of versions of the same package

```
hunan/data                                       2c2caeb3
hunan/data                                       4f7dec20
hunan/data                                       6aa0f6e2
hunan/data                                       7860bf0f
hunan/data                                       a07a0847
hunan/data                  latest               0faf1a74
```

And would like to inspect the contents of say `4f7dec20`.

Thanks

**Comment by akarve** [comment]
This is now possible by working with (or iterating over) Quilt 3 package manifests.
