### ISSUE TITLE
CLI - Team login with custom registry

### ISSUE THREAD

**Issue by johngroves** [quiltdata/quilt#695]
The [_check_team_exists](https://github.com/quiltdata/quilt/blob/master/compiler/quilt/tools/command.py#L362) and [get_registry_url](https://github.com/quiltdata/quilt/blob/master/compiler/quilt/tools/command.py#L132) functions use a hard-coded string template to build the registry url rather than loading the registry_url from the config, preventing teams logins when using a custom registry.

**Comment by kevinemoore** [comment]
This is fixed in #793. Users can now run `quilt config TEAM` to specify a custom URL for their private Teams Registry.
