### ISSUE TITLE
Package variables are not identified

### ISSUE THREAD

**Issue by earthat** [quiltdata/quilt#728]
Hi

I am trying to import the package from the [link.](https://quiltdata.com/package/kmoore/sat4_6_airborne) But its not accessing the variables in sat_6_full further. Its a data node. I am trying it as 

```
from quilt.data.kmoore import sat4_6_airborne
sat4_6_airborne.sat_6_full.train_x()
```

**Comment by akarve** [comment]
Example notebook added here:
https://github.com/quiltdata/examples/blob/master/matlab/Satellite%20images.ipynb
