### ISSUE TITLE
Programmatic remove from Local

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#742]
No way currently to remove a set of packages.

Current process:
```
$ quilt ls
...
$ quilt rm usr/pkg
$ quilt rm usr/pkg
```

Would like the ability to remove where condition matches regex:
```
$ quilt rm ^usr/*
```

Or some other programmatic interface for removal. Not necessarily regex.

**Comment by akarve** [comment]
Quilt 3 API provides constant for cache directory as well as a flush cache command.
