### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by sergeny** [quiltdata/quilt#753]
I took test_v2.csv from the Kaggle Loan Default Prediction dataset (https://www.kaggle.com/c/loan-default-prediction/data).
It is a 1Gb file. I wanted to upload it to my free quilt account, to test it.

    import pandas as pd
    df = pd.read_csv('./test_v2.csv')
    quilt.build('...', df)
    quilt.push('...', is_public=True)

See screenshot. Restricting the dataframe to df[:1000] works just fine.

<img width="942" alt="screen shot 2018-08-15 at 11 27 34 pm" src="https://user-images.githubusercontent.com/5010099/44187216-6f021900-a0ea-11e8-834c-6122f79fa7e2.png">

**Comment by eode** [comment]
What version of Pandas are you using?

Also, can I get a full copy-paste of that traceback rather than a screenshot?

**Comment by akarve** [comment]
Closed after no response and since we have migrated to Quilt 3.
