### ISSUE TITLE
Columns QC check

### ISSUE THREAD

**Issue by gte620v** [quiltdata/quilt#756]
I have checks that look like the following to check that the desired columns are present in my dataframe.  It would be nice if there was a built-in qc function for that.  

```
checks:
  has_common_cols: |
    goal = ['col1', 'col2', 'col3']
    qc.check(sum([current in qc.data.columns for current in goal]) == len(goal))
```

**Comment by akarve** [comment]
To be handled in Quilt 3 via CI/CD for data roadmap.
