### ISSUE TITLE
Support for azure blob storage instead of S3

### ISSUE THREAD

**Issue by kodonnell** [quiltdata/quilt#761]
Quoting https://docs.quiltdata.com/support/faq :

> Where are my data stored? ... Running your own registry - up to you :-)

I can't seem to find any documentation around this. Specifically, we'd like to use Azure Blob Storage. If Azure isn't supported but it could be (relatively easily) then maybe someone could quickly point out areas of the code that'd need to change? Or is quilt too tightly wed to S3?

Or - should I use something like https://github.com/minio/minio?

EDIT: added minio option.

**Comment by kodonnell** [comment]
Great stuff! If there was an easy way to e.g. structure these storage layers as contrib modules, and there was one example (i.e. S3) then others (like me) could easily contribute/maintain other modules etc. Then again, PRs might make sense for the big players (Google/Microsoft).

**Comment by akarve** [comment]
Agree. In Quilt 3, (now in Alpha, lmk if you want a preview), the interaction with storage should be cleaner. Eventually where we want to get is something like minio or ceph -- both of which are API identical to S3 but can write anywhere you wish.

**Comment by akarve** [comment]
Work ongoing in #769

**Comment by akarve** [comment]
To be handled via Roadmap item on min.io
