### ISSUE TITLE
[ENH] upload parquet files directly

### ISSUE THREAD

**Issue by knaaptime** [quiltdata/quilt#780]
Hi team,

thanks for the great work on this project. With the current behavior when users have tabular data like CSV, its gets converted to parquet upon `quilt push`. But, when the data are *already* stored as a series of parquet files, the binaries are simply uploaded to the quilt server and the underlying dataframes aren't registered under `tables/`

is it possible to allow uploading of parquet files directly so that the dataframes are registered and useable?

**Comment by kevinemoore** [comment]
Yes, single parquet files are definitely supported. We might need to add some extra logic to correctly pickup folder-level metadata for partitioned tables in parquet. @knaaptime, are you using partitioned tables?

**Comment by knaaptime** [comment]
no, but i'm using the built-in gzip compression on the parquet files, so that's probably causing some trouble

https://quiltdata.com/package/knaaptime/census

**Comment by kevinemoore** [comment]
@knaaptime, I looked at your package: [https://quiltdata.com/package/knaaptime/census](url). The input files have the extension .parquet.gzip. Are those gzipped parquet files? Or, just parquet files that use gzip internally? If it's the latter, try adding: `transform: parquet` in your build file (you might need to create a build file using `quilt generate`).

**Comment by knaaptime** [comment]
awesome, thank you.

the files are created with `pd.to_parquet(compression='gzip')`, so I think the latter? I could probably just recreate without compression (or using a different algo) to make things simpler

**Comment by robnewman** [comment]
@knaaptime -- If you still need compression of your files, by default `pd.to_parquet()` uses `snappy` as the compression algo. You have to specify `compression=None` for no compression algo. [More info](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_parquet.html)

**Comment by kevinemoore** [comment]
Definitely use whichever compression makes most sense for your use cases, just try explicitly setting the transform, which will set the appropriate metadata in the package that will tell Quilt to read that node as a DataFrame when its _data() method is called.

**Comment by knaaptime** [comment]
ok, I uploaded a new version that uses brotli compression and eschews a file extension beyond `.parquet`. Everything's working beautifully. 

thanks folks!

**Comment by kevinemoore** [comment]
That's great! I installed your package and got DataFrames. It worked great for me too.

**Comment by knaaptime** [comment]
for bonus points you can convert back to spatial data with

```python
import geopandas as gpd
from quilt.data.knaaptime import census
from shapely.wkb import loads

df = census.tracts_1990()
df['geometry'] = df.wkb.apply(lambda x: loads(x, hex=True))
df = gpd.GeoDataFrame(df)
```

😉
