### ISSUE TITLE
List metadata for a package

### ISSUE THREAD

**Issue by limx0** [quiltdata/quilt#782]
Somewhat related to #497, it would be quite useful to be able to list all of the metadata for a package. 

For example; I might have some package stock data package (financial time series) that I generate for a list of symbols / stocks and some given time frequency (tick or 1 minute bars). I might publish it with the meta `{'symbol': 'AAPL', 'frequency': 'tick'}`. 

From a user perspective, it would be useful to be able to see a list / table of metadata for the package. A user might want to see if a given stock exists, or some other arbitrary metadata.

**Comment by akarve** [comment]
Agreed. In Quilt 3 (a.k.a.) T4 we have much easier ways of dealing with medata. The manifests are line-based JSON with human-readable metadata and can be sliced using S3 Select: https://quiltdocs.gitbook.io/t4/advanced-usage/s3-select

**Comment by akarve** [comment]
And you can directly interact with the metadata as follows:
https://quiltdocs.gitbook.io/t4/api-reference/package#Package.get\_meta

**Comment by akarve** [comment]
Fixed via package iteration in Quilt 3 which allows for interaction with arbitrary metadata and filtering upon the same
