### ISSUE TITLE
How to login in a python  program ?

### ISSUE THREAD

**Issue by bussiere** [quiltdata/quilt#807]
i would like to know how to automatically login inside a batch python program with quit ?

is there a way to pass login / password to quilt.login ?

**Comment by akarve** [comment]
We plan to make this easier in the Quilt 3, but for now, you can do the following:
https://docs.quiltdata.com/support/faq#how-to-access-private-packages-from-a-remote-machine-without-quilt-login

**Comment by mjmikulski** [comment]
@akarve Any updates on this issue? What is preferred way to log in in a python script in `quilt3`?
