### ISSUE TITLE
can't access to a pushed quilt

### ISSUE THREAD

**Issue by bussiere** [quiltdata/quilt#808]
so in a notebook i've created and pushed a quilt : 

https://quiltdata.com/package/bussiere/test

```
from quilt.data.bussiere import test
#del test
test._set(["Rue"],df)
quilt.build("bussiere/test", "quilt")
quilt.login()
quilt.push("bussiere/test",is_public=True)
```

but i cannot access it as the example : 

```
import quilt
quilt.install("bussiere/test")
from quilt.data.bussiere import test
test.table.Rue()
```
or

```
import quilt
quilt.install("bussiere/test")
from quilt.data.bussiere import test
test.Rue()
```

I have a key error for both
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/share/virtualenvs/GeoMasterMicro-uG6MrMuJ/lib/python3.7/site-packages/quilt/nodes.py in __getattr__(self, name)
     97             try:
---> 98                 return self[name]
     99             except KeyError:

~/.local/share/virtualenvs/GeoMasterMicro-uG6MrMuJ/lib/python3.7/site-packages/quilt/nodes.py in __getitem__(self, name)
    128     def __getitem__(self, name):
--> 129         return self._children[name]
    130 

KeyError: 'table'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-20-6fcea0b5e403> in <module>
----> 1 test.table.Rue()

~/.local/share/virtualenvs/GeoMasterMicro-uG6MrMuJ/lib/python3.7/site-packages/quilt/nodes.py in __getattr__(self, name)
     98                 return self[name]
     99             except KeyError:
--> 100                 raise AttributeError
    101 
    102     def __setattr__(self, name, value):

AttributeError:

**Comment by akarve** [comment]
Hi. I just tried the following steps and was able to access the data. Can you do a `pip install quilt --upgrade`, then follow these steps, and let me know if it works for you?

`$ quilt install bussiere/test`

In [5]: from quilt.data.bussiere import test                                    

In [6]: test.Rue()                                                              
Out[6]: 
      id                 created  ... codeCadastre commune
0    1.0 2019-01-03 17:27:33.562  ...         None  3474.0
1    2.0 2019-01-03 17:28:06.775  ...         None  3474.0
2    3.0 2019-01-03 17:28:07.711  ...         None  3474.0
3    4.0 2019-01-03 17:28:26.385  ...         None  3474.0
4    5.0 2019-01-03 17:28:27.321  ...         None  3474.0
5    6.0 2019-01-03 17:32:53.822  ...         None  3474.0
6    7.0 2019-01-03 17:32:56.318  ...         None  3474.0
7    8.0 2019-01-03 17:32:56.723  ...         None  3474.0
8    9.0 2019-01-03 17:32:57.035  ...         None  3474.0
9   10.0 2019-01-03 17:32:59.656  ...         None  3474.0
10  11.0 2019-01-03 17:32:59.968  ...         None  3474.0
11  12.0 2019-01-03 17:33:01.279  ...         None  3474.0
12  13.0 2019-01-03 17:33:03.385  ...         None  3474.0
13  14.0 2019-01-03 17:33:04.711  ...         None  3474.0
14  15.0 2019-01-03 17:33:09.843  ...         None  3474.0
15  16.0 2019-01-03 17:33:12.885  ...         None  3474.0
16  17.0 2019-01-03 17:33:13.384  ...         None  3474.0
17  18.0 2019-01-03 17:33:15.896  ...         None  3474.0
18  19.0 2019-01-03 17:33:16.629  ...         None  3474.0
19   NaN                     NaT  ...         None     NaN

[20 rows x 17 columns]

**Comment by akarve** [comment]
Note that `test.table.Rue` will not work because that path is note defined in the code shown above

**Comment by bussiere** [comment]
It was the path thanks
