### ISSUE TITLE
Ability to limit how many processes are spawned during hashing

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#822]
Currently there is no option to set the max number of threads to be opened during file hashing.
https://github.com/quiltdata/t4/blob/master/api/python/t4/data_transfer.py#L654

Would appreciate either the ability to set and environment variable that gets picked up or pass a parameter.

**Comment by akarve** [comment]
@JacksonMaxfield is this still an issue? In the last few months we've completed many hashing performance improvements. Please reopen if you'd still like control over the number of processes.

**Comment by JacksonMaxfield** [comment]
Very low priority.
