### ISSUE TITLE
Fetch target should check for existing

### ISSUE THREAD

**Issue by JacksonMaxfield** [quiltdata/quilt#824]
Open for discussion:

Currently `PackageEntry.fetch` will overwrite any file that already exists at the filepath provided. I understand not trusting filenames but I believe hashing the files present at the location then checking the incoming hash to that location and skipping if it is the same could be a big time and transfer save.

In the case a directory is provided to `fetch`, it would check the `directory / incoming.name` hash. In the case a full path is provided to `fetch`, check the fullpath hash against the incoming hash.

**Comment by akarve** [comment]
The new hotness is that `install` now supports caching and will use the local copy whenever possible. Please reopen if that is not the case or if that is not sufficient.
