### ISSUE TITLE
How to use quilt3 to access quiltdata packages?

### ISSUE THREAD

**Issue by zyrikby** [quiltdata/quilt#931]
Hi,

In the documentation, it is written that currently quilt utility is moving to version 3. I checked the documentation, and it is not clear how quilt3 could be used to access data on quiltdata (uploaded with quilt). Moreover, there is no information what is the reason for the development of quilt3 API (that is quite different from quilt2).

Could you please guide me where I can find this information?

**Comment by akarve** [comment]
Hi. We will likely provide a utility script that moves Quilt 2 packages to Quilt 3, or do the migration automatically in the coming weeks. The Quilt 3 API is similar to, but not the same as the Quilt 2 API. We designed Quilt3 for better first-class integration with S3, improved scale, and performance.

You can read about some of the design motivations (and the new API) here:
https://blog.quiltdata.com/rethinking-s3-announcing-t4-a-team-data-hub-8e63ce7ec988
https://docs.quiltdata.com/

**Comment by akarve** [comment]
Presently there is no way to access Quilt 2 packages with Quilt 3 (we will address this as stated above). But you may continue to use both services uninterrupted via the `quilt` and `quilt3` PyPI packages.

**Comment by zyrikby** [comment]
Thanks for the reply. I read the links that you've provided, however, the intentions were not clear to me. Now, I understand what are the reasons behind the choice of implementation of the new version.
